stages:
  - merge-master>homolog 
  - merge-homolog>homolog-qa
  - merge-homolog>dev

Merge-Master > Homolog:
  image: bitnami/git:2.42.1 
  stage: merge-master>homolog
  tags:
    - merge

  script: 
    - export CI_JOB_TOKEN="VxHD9hiXy2FzMMoetzzp"
    - git config --global user.email "desenvolvimento@sifat.com.br"
    - git config --global user.name "gitlab auto-merge"
    - git status
    - git add .
    - git fetch
    - git checkout homolog && git pull --allow-unrelated-histories # Checkout na branch que irá receber o merge
    - echo $CI_COMMIT_REF_NAME
    - |
      if git merge origin/$CI_COMMIT_REF_NAME --allow-unrelated-histories; then
        echo "Merge bem-sucedido!"
      else
        echo "Erro durante o merge. Enviando notificação para Discord..."
        curl -H "Content-Type: application/json" -X POST -d '{"content": "Erro durante o merge na pipeline GitLab: '$CI_COMMIT_REF_NAME' para homolog. Verifique o merge manualmente."}' https://discord.com/api/webhooks/1222534933277442078/pQbEUdTAi7o7bUug73_i8_mUfdiiS1MGBwVKs_JaajzleDBwdq2WGlLHTWwO6Odtn7Xn
        exit 1
      fi
    - git push --force "http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sifat.com.br:8888/waybe-api-microsservicos/api-devops.git"

  only:
    - master 
 

Merge-Homolog > Dev:
  image: bitnami/git:2.42.1
  stage: merge-homolog>dev
  tags:
    - merge

  script: 
    - export CI_JOB_TOKEN="VxHD9hiXy2FzMMoetzzp"
    - git config --global user.email "desenvolvimento@sifat.com.br"
    - git config --global user.name "gitlab auto-merge"
    - git status
    - git add .
    - git fetch
    - git checkout dev && git pull --allow-unrelated-histories # Checkout na branch que irá receber o merge
    - echo $CI_COMMIT_REF_NAME
    - |
      if git merge origin/$CI_COMMIT_REF_NAME --allow-unrelated-histories; then
        echo "Merge bem-sucedido!"
      else
        echo "Erro durante o merge. Enviando notificação para Discord..."
        curl -H "Content-Type: application/json" -X POST -d '{"content": "Erro durante o merge na pipeline GitLab: '$CI_COMMIT_REF_NAME' para homolog. Verifique o merge manualmente."}' https://discord.com/api/webhooks/1222534933277442078/pQbEUdTAi7o7bUug73_i8_mUfdiiS1MGBwVKs_JaajzleDBwdq2WGlLHTWwO6Odtn7Xn
        exit 1
      fi    
    - git merge origin/$CI_COMMIT_REF_NAME --allow-unrelated-histories # Nao remover ORIGIN
    - git push --force "http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sifat.com.br:8888/waybe-api-microsservicos/api-devops.git"

  only:
    - homolog   
    
Merge-Homolog > Homolog-qa:
  image: bitnami/git:2.42.1
  stage: merge-homolog>homolog-qa
  tags:
    - merge

  script: 
    - export CI_JOB_TOKEN="VxHD9hiXy2FzMMoetzzp"
    - git config --global user.email "desenvolvimento@sifat.com.br"
    - git config --global user.name "gitlab auto-merge"
    - git status
    - git add .
    - git fetch
    - git checkout homolog-qa && git pull --allow-unrelated-histories # Checkout na branch que irá receber o merge
    - echo $CI_COMMIT_REF_NAME
    - |
      if git merge origin/$CI_COMMIT_REF_NAME --allow-unrelated-histories; then
        echo "Merge bem-sucedido!"
      else
        echo "Erro durante o merge. Enviando notificação para Discord..."
        curl -H "Content-Type: application/json" -X POST -d '{"content": "Erro durante o merge na pipeline GitLab: '$CI_COMMIT_REF_NAME' para homolog. Verifique o merge manualmente."}' https://discord.com/api/webhooks/1222534933277442078/pQbEUdTAi7o7bUug73_i8_mUfdiiS1MGBwVKs_JaajzleDBwdq2WGlLHTWwO6Odtn7Xn
        exit 1
      fi    
    - git merge origin/$CI_COMMIT_REF_NAME --allow-unrelated-histories # Nao remover ORIGIN
    - git push --force "http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sifat.com.br:8888/waybe-api-microsservicos/api-devops.git"

  only:
    - homolog