stages:
  - merge-master>homolog
  - merge-homolog>homolog-qa
  - merge-homolog>dev

Merge-Master > Homolog:
  image: bitnami/git:2.42.1 
  stage: merge-master>homolog
  tags:
    - merge

  script: 
    - git config --global user.email "desenvolvimento@sifat.com.br"
    - git config --global user.name "gitlab auto-merge"
    - export CI_JOB_TOKEN="sLMKoJYV163rFyV1AQDs"
    - git status
    - git add .
    - git fetch
    - git checkout homolog && git pull --allow-unrelated-histories # Checkout na branch que irá receber o merge
    - echo $CI_COMMIT_REF_NAME
    - git merge origin/$CI_COMMIT_REF_NAME --allow-unrelated-histories # Nao remover ORIGIN
    - git push --force http://gitlab+deploy-token-1:deploy-waybe-microsservicos@gitlab.sifat.com.br:8888/waybe-microsservicos/api-teste-devops.git

  only:
    - master 

Merge-Homolog > Homolog-qa:
  image: bitnami/git:2.42.1
  stage: merge-homolog>homolog-qa
  tags:
    - merge

  script: 
    - git config --global user.email "desenvolvimento@sifat.com.br"
    - git config --global user.name "gitlab auto-merge"
    - export CI_JOB_TOKEN="sLMKoJYV163rFyV1AQDs"
    - git status
    - git add .
    - git fetch
    - git checkout homolog-qa && git pull --allow-unrelated-histories # Checkout na branch que irá receber o merge
    - echo $CI_COMMIT_REF_NAME
    - git merge origin/$CI_COMMIT_REF_NAME --allow-unrelated-histories # Nao remover ORIGIN
    - git push --force http://gitlab+deploy-token-1:deploy-waybe-microsservicos@gitlab.sifat.com.br:8888/waybe-microsservicos/api-teste-devops.git

  only:
    - homolog

Merge-Homolog > Dev:
  image: bitnami/git:2.42.1
  stage: merge-homolog>dev
  tags:
    - merge

  script: 
    - git config --global user.email "desenvolvimento@sifat.com.br"
    - git config --global user.name "gitlab auto-merge"
    - export CI_JOB_TOKEN="sLMKoJYV163rFyV1AQDs"
    - git status
    - git add .
    - git fetch
    - git checkout dev && git pull --allow-unrelated-histories # Checkout na branch que irá receber o merge
    - echo $CI_COMMIT_REF_NAME
    - git merge origin/$CI_COMMIT_REF_NAME --allow-unrelated-histories # Nao remover ORIGIN
    - git push --force http://gitlab+deploy-token-1:deploy-waybe-microsservicos@gitlab.sifat.com.br:8888/waybe-microsservicos/api-teste-devops.git

  only:
    - homolog         
